### ISSUE TITLE
JSDOM Issue before all" hook: Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

### ISSUE THREAD

**Issue by ApurvaB** [rstacruz/jsdom-global#10]
I was getting 
before all" hook:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
 For

```
before(function () {
  this.jsdom = require('jsdom-global')()
})

after(function () {
  this.jsdom()
})
```

Changing above lines code to  import statement below resolved the issue.

```
import 'jsdom-global/register'; 
```

**Stating here , so in case anybody else encounter the same will have a solution.**  Thanks!

**Comment by rstacruz** [comment]
It looks like you did before(function(done)...) with an argument.

**Comment by ApurvaB** [comment]
Nope! Just as I have mentioned ..without argument.

```
before(function () {
  this.jsdom = require('jsdom-global')()
})

after(function () {
  this.jsdom()
})
```

**Comment by rstacruz** [comment]
Alright. Thanks for the report! I'm closing this issue now as it's been resolved. If anyone can replicate the issue, please leave a note.

**Comment by DylanRJohnston** [comment]
I just came across the issue as well, it seems initialising jsdom sometimes takes a while, setting the timeout higher solves the issue

```ts
  let cleanup: () => void

  before(function() {
    this.timeout(5000)

    cleanup = jsdom('', { url: 'http://localhost' })
  })

  after(() => {
    cleanup()
  })
```

**Comment by DylanRJohnston** [comment]
Weirdly enough, instrumenting it, it only seems to take ~500ms

```ts
let cleanup: () => void

  before(function() {
    // this.timeout(5000)

    const start = process.hrtime()
    cleanup = jsdom('', { url: 'http://localhost' })
    console.log(`Loading took ${process.hrtime(start)[1] / 1000000}ms`)
  })

  after(() => {
    cleanup()
  })
```
