### ISSUE TITLE
pass the options to jsdom

### ISSUE THREAD

**Issue by kenjiru** [rstacruz/jsdom-global#3]
For mocking REST calls made with CujoJS rest package (https://github.com/cujojs/rest), we need to specify the location, otherwise it fails.

According to https://github.com/tmpvar/jsdom#for-the-hardcore-jsdomjsdom this can be done using the second _options_ parameter.

``` javascript
var document = jsdom.jsdom(html, {
    url: "http://localhost"
});
```

I would make even the html parameter configurable. Or course, provide a default value, but offer the user the possibility to change it, if he needs to.

**Comment by rstacruz** [comment]
oh, neat. I think we can do this:

``` js
// This is not implemented in v1.x.x, FYI.
jsdom = require('jsdom-global')
jsdom({ url: "http://localhost" })
jsdom(html, { url: "http://localhost" })
```

If we do this I'm going to deprecate the (undocumented) use of `jsdom(function () { ... })`, which was a pretty dumb feature anyway haha.

**Comment by rstacruz** [comment]
...might as well add #2 in there, and release it as 2.0.0.

**Comment by kenjiru** [comment]
I usually try to avoid overloading the parameters. I consider better practice to expect a fixed number of parameters, and provide default values for the ones that are undefined.

This is exactly what `jsdom.jsdom()` does anyway, so we would use a consistent pattern.

``` javascript
function jsdom(html, options) {
    if (html === undefined) {
        html = defaultHtml;
    }

    if (options === undefined) {
        options = {};
    }
}
```

Then a client that wants to provide the options but use the default html, would have to provide `undefined` for the first parameter.

``` javascript
jsdom(undefined, {
    url: "http://localhost"
});
```

Here's the reference to the jsdom implementation:
https://github.com/tmpvar/jsdom/blob/master/lib/jsdom.js#L66

**Comment by rstacruz** [comment]
I'm cool with that... Indeed the flexible parameters was a bit more of a
Ruby-ism, lol.

**Comment by kenjiru** [comment]
Would you accept a pull request or you want to implement it yourself?
