### ISSUE TITLE
Unix only?

### ISSUE THREAD

**Issue by DoctorDerek** [rstacruz/jsdom-global#55]
This is how it crashes for me:
```
npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path C:\dev\React-TDD-Gift-Giver\node_modules\acorn-globals\node_modules\acorn
npm ERR! dest C:\dev\React-TDD-Gift-Giver\node_modules\acorn-globals\node_modules\.acorn.DELETE
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\dev\React-TDD-Gift-Giver\node_modules\acorn-globals\node_modules\acorn' -> 'C:\dev\React-TDD-Gift-Giver\node_modules\acorn-globals\node_modules\.acorn.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\derek\AppData\Roaming\npm-cache\_logs\2020-11-30T22_48_51_788Z-debug.log
```

This was with
```
npm install --save-dev --save-exact jsdom jsdom-global
```

**Comment by DoctorDerek** [comment]
It worked after restarting the terminal 😂😅

**Comment by rstacruz** [comment]
Thanks for the report! It might be worth exploring other more modern alternatives. Jest, for instance, offers built in jsdom support out of the box.

**Comment by DoctorDerek** [comment]
@rstacruz Great point! While Jest may support jsdom out of the box, Enzyme doesn't... and is starting to look a bit like abandonware -- it hasn't had a major release in a year.

I needed to switch from Enzyme's "shallow" to "mount" functionality to test functionality for a project using React Hooks to manage state, so your package was still very helpful! 🙏

I'd definitely consider starting with React Testing Library instead for my next project. Cheers!
