### ISSUE TITLE
Globalizing window keys

### ISSUE THREAD

**Issue by amsul** [rstacruz/jsdom-global#6]
Please see: https://github.com/tmpvar/jsdom/issues/1549

From their changelog for v9.4.0:

> Fixed all constructors that appears as globals on the jsdom window object to be non-enumerable.

This means that these lines no longer work: https://github.com/rstacruz/jsdom-global/blob/bc52cfefbfe9931e6c367d38cdd8a60cd216dce8/index.js#L37-L41

``` js
Object.keys(window).forEach(function (key) {
  if (blacklist.indexOf(key) !== -1) return
  keys.push(key)
  global[key] = window[key]
}))
```

I'm not exactly sure if they have a better API to allow globalizing the window properties.. So I'm waiting for a reply until I can suggest a solution. But maybe you have some thoughts around this.

Cheers!

**Comment by rstacruz** [comment]
Interesting, I'm gonna guess we can just maintain a hard-coded list of
keys.

**Comment by amsul** [comment]
@rstacruz or https://github.com/rstacruz/jsdom-global/pull/7 :)

**Comment by amsul** [comment]
Solved with https://github.com/rstacruz/jsdom-global/pull/7#issuecomment-241359955
