### ISSUE TITLE
Stupid Question About JSDom

### ISSUE THREAD

**Issue by machineghost** [rstacruz/jsdom-global#8]
I'm sure there's a very good reason for this, but since I'm not aware of it I had to ask: why tell people to install the JSDom module separately, when you could just make it a dependency of jsdom-global?

**Comment by gregaou** [comment]
I'm also interested in the answer

**Comment by rstacruz** [comment]
It's so you can manage the dependency version yourself. If jsdom-global has
a dependency for (example) jsdom@^9.0.0, there's no way for you to pin
jsdom to whatever version you want unless you use `npm shrinkwrap`. (This
was recently relevant when jsdom@9.4.0 broke jsdom-global behavior, which
has since been fixed).

**Comment by machineghost** [comment]
I'm curious: what percentage of users you think actually want to have a different JSDom version from the one `jsdom-global` expects?

**Comment by rstacruz** [comment]
Absolutely no clue!

**Comment by machineghost** [comment]
Well I suspect it is somewhere between a tiny percentage and 0%.  And while I certainly wouldn't begrudge you supporting that minority, I would suggest that doing things which benefit the vast majority of your users would ... well, benefit the vast majority of your users :)

**Comment by rstacruz** [comment]
Thanks for voicing out your concerns. I'm afraid I'm going to decline based on an admittedly very selfish reason: I'm part of that low percentage of users who need it :) 

I'd wager to guess most people who prefer --save-exact and/or use greenkeeper.io would be interested in locking jsdom versions. In fact, I think everyone should care about it, Here's why... 

Jsdom is a very complex and fast moving library. It ships new major versions quite frequently. It also doesn't exactly follow semver, there are changes in 9.4.0 that would break what was working in 9.3.0 -- with a surface area that huge, it's really bound to happen and I can't fault them for that. 

This is compounded by the fact that jsdom-global deliberately goes against jsdom maintainer's recommendations. Their docs specially warn against promoting jsdom's artifacts as globals, which is exactly what jsdom-global does. In short, jsdom's maintainers does not support jsdom-global's use case and jsdom-global breakage is a high possibility with new jsdom versions. 

Locking your jsdom version (eg,  "jsdom" :"9.4.2" versus "jsdom":"^9.0.0") is an assurance that your tests will work in the future. Should a change in 9.4.3 break your code, it wouldn't matter--your project is locked onto 9.4.2.

Jsdom-global can try one of 3 things:
- list jsdom as a direct dependency at a locked version (eg, jsdom 9.4.2). I would rather not do this, I don't want the burden of checking every jsdom release if they're compatible and bumping jsdom-global accordingly.
- list jsdom as a dependency with a version range (eg, jsdom >=9). This is less maintenance burden, but locking jsdom versions would be _impossible_. This has caused headaches in other libraries like babel.
- or we can just keep it the way it is now (jsdom as a peer dependency). Those who wish to lock the version can do so. Those who wish to use a version range can do so as well. The only price is a minor inconvenience of an extra 6 characters to type into your one-time `npm install`.

In the end, I think the benefits greatly outweigh the cost here.

**Comment by machineghost** [comment]
Fair enough: as I said, I certainly won't begrudge you for supporting your users :+1:
